<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DucAnh" failures="1" tests="12" name="apitest.Bai1" time="162.485" errors="0" timestamp="2020-04-29T09:46:23 ICT" skipped="0">
  <testcase classname="apitest.Bai1" name="bai4" time="10.486"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai8PrintTokyo" time="6.474"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai10" time="6.812">
    <failure message="expected [13] but found [15]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [13] but found [15]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at apitest.Bai1.bai10(Bai1.java:222)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- bai10 -->
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai8PrintNewYork" time="6.681"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai11" time="6.188"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai7" time="9.799"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai9" time="7.906"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai5" time="72.818"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai1" time="10.907"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai2" time="10.893"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai6" time="7.284"/>
  <system-out/>
  <testcase classname="apitest.Bai1" name="bai3" time="6.237"/>
  <system-out/>
</testsuite> <!-- apitest.Bai1 -->
